title: "LLVM 初心者が JIT コンパイラに挑戦"
summary: "挑戦してみます．これはほぼ自分用のメモとして書いてます．コード： https://github.com/fiveseven-lambda/toy_language 気長にやります．"
topics: [cpp, llvm]
published: true
price: 0
chapters:
  - specification
  - error
  - token
  - lexer
