title: "AtCoder と Rust で始める！競技プログラミング入門（Rust 版 APG4b）"
summary: "APG4b ( https://atcoder.jp/contests/APG4b ) の Rust 版が欲しかったので書き始めました．少しずつ書き進めていきたいと思います．"
topics: ["rust", "atcoder"]
published: true
price: 0
chapters:
  - 01-intro
  - 02-output
  - 03-error
  - 04-integer
  - 05-variable
  - 06-literal
  - 07-input
  - 08-if
  - 09-block
  - 10-assert
  - 11-tuple
  - 12-array
  - 13-format
