title: "AtCoder と Rust で始める！競技プログラミング入門（Rust 版 APG4b）"
summary: "APG4b ( https://atcoder.jp/contests/APG4b ) の Rust 版が欲しかったので書き始めました．少しずつ書き進めていきたいと思います．更新履歴は github ( https://github.com/fiveseven-lambda/zenn/commits/main/books/apg4b-rust-ver ) から見られます．内容に関する意見や指摘などはスクラップ ( https://zenn.dev/toga/scraps/29283c8c5f3d16 ) に残していただくか， twitter ( https://twitter.com/57tggx ) あるいは misskey ( https://misskey.io/@five_seven ) までお願いします．"
topics: ["rust", "atcoder"]
published: true
price: 0
chapters:
  - 01-intro
  - 02-output
  - 03-error
  - 04-integer
  - 05-variable
  - 06-literal
  - 07-input
  - 08-if
  - 09-block
  - 10-assert
  - 11-tuple
  - 12-array
  - 13-format
  - 14-reference
  - 15-for
  - 16-pattern
  - 17-mutable
  - 18-mutable-reference
  - 19-vector
  - 20-loop
  - 21-slice
  - 22-match
  - 23-string
  - 24-ownership
  - 25-function
  - 26-call-by-reference
  - 27-boolean
  - 28-recursion
  - 29-bitwise-operation
  - 30-complexity
